# Generated by Django 4.2.1 on 2023-05-26 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
import verification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None)),
                ('username', models.CharField(default=None, max_length=150, null=True)),
                ('token', models.PositiveIntegerField(default=verification.models.verification_token)),
                ('secret', models.UUIDField(default=None, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(('phone_number__isnull', False), ('email__isnull', False), ('username__isnull', False), _connector='OR'), name='at_least_one_type'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(('phone_number__isnull', False), ('email__isnull', False), _negated=True), name='not_both_phone_and_email'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(('phone_number__isnull', False), ('username__isnull', False), _negated=True), name='not_both_phone_and_username'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False), ('username__isnull', False), _negated=True), name='not_both_email_and_username'),
        ),
    ]
